changelog:
  categories:
    - title: Nowości
      labels:
        - enhancement
    - title: Poprawki
      labels:
        - bug
    - title: Dokumentacja
      labels:
        - documentation
    - title: CI i automatyzacja
      labels:
        - dependencies
        - github_actions
