[user_preferences]
default_cinema = "Cinema City"               # available choices: ["Cinema City" | "Helios" | "Multikino"]
default_cinema_venue = "Wrocław - Wroclavia" # check list of available cinemas in db or at cinema' website
default_day = "today"                        # ["today" | "tomorrow"]


[db]
db_file_path = "db.sqlite"  # relative to project root

[cinemas_urls.cinema_city]
repertoire_url = "https://www.cinema-city.pl/#/buy-tickets-by-cinema?in-cinema={cinema_venue_id}&at={repertoire_date}"
venues_list_url = "https://www.cinema-city.pl/#/buy-tickets-by-cinema"

[cinemas_urls.helios]
repertoire_url = ""
venues_list_url = ""

[cinemas_urls.multikino]
repertoire_url = ""
venues_list_url = ""
