[tool.poetry]
name = "cinema-repertoire-analyzer"
version = "0.1.0"
description = ""
authors = ["Jan Wadolowski <janwadolowski@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
requests-html = "^0.10.0"
requests = "^2.26.0"
PyYAML = "^6.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
types-PyYAML = "^6.0.1"
types-requests = "^2.26.2"
mypy = "^0.930"
black = "^22.12.0"
bandit = "^1.7.4"
isort = "^5.11.4"
autoflake = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
