[tool.poetry]
name = "cinema-repertoire-analyzer"
version = "0.1.0"
description = ""
authors = ["Jan Wadolowski <janwadolowski@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
typer = "^0.7.0"
loguru = "^0.6.0"
sqlalchemy = "^2.0.6"

[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.3.0"
pylama = { extras = ["all"], version = "^8.4.1" }
mypy = "^0.991"
bandit = "^1.7.4"
autoflake = "^2.0.0"
pytest = "^7.2.1"
isort = "^5.11.4"
black = "^22.12.0"
flake8-pyproject = "^1.2.2"
types-pyyaml = "^6.0.12.8"
mockito = "^1.4.0"
types-toml = "^0.10.8.5"
pytest-cov = "^4.0.0"
pre-commit = "^3.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
preview = true
exclude = '''
(
    __pycache__
)
'''

[tool.flake8]
max-line-length = 88
count = true
exclude = [".git", "__pycache__"]
per-file-ignores = ["__init__.py: F401"] # imported but unused
max-complexity = 10

[tool.pylama]
format = "pylint"
skip = "*/.tox/*,*/.env/*"
linters = [
  "eradicate",
  "mccabe",
  "mypy",
  "pycodestyle",
  "pydocstyle",
  "pylint",
  "isort",
]
