# set your preferences here
default_date = "dzisiaj" # dzisiaj, jutro, pojutrze
default_cinema_chain = "cinema city"
default_cinema_venue = "Wrocław - Wroclavia"
user_input_date_format = "%d.%m.%Y" # dd.mm.yyyy

# app config, do not change unless url no longer work on provider site
# you don't need to update venues manually, just run app with update command
[cinema_city]
repertoire_url = "https://www.cinema-city.pl/#/buy-tickets-by-cinema?in-cinema={cinema_id}&at={date}"
    [cinema_city.venues]
    "Bielsko-Biała" = 1_088
    Bydgoszcz = 1_086
    Bytom = 1_092
    Cieszyn = 1_098
    "Częstochowa - Galeria Jurajska" = 1_089
    "Częstochowa - Wolność" = 1_075
    Gliwice = 1_085
    "Katowice - Punkt 44" = 1_065
    "Katowice - Silesia" = 1_079
    "Kraków - Bonarka" = 1_090
    "Kraków - Galeria Kazimierz" = 1_076
    "Kraków - Zakopianka" = 1_064
    "Lublin - Felicity" = 1_094
    "Lublin - Plaza" = 1_084
    "Poznań - Kinepolis" = 1_081
    "Poznań - Plaza" = 1_078
    "Ruda Śląska" = 1_062
    Rybnik = 1_082
    Sosnowiec = 1_083
    "Starogard Gdański" = 1_095
    "Toruń - Czerwona Droga" = 1_077
    "Toruń - Plaza" = 1_093
    "Warszawa -  Arkadia" = 1_074
    "Warszawa - Bemowo" = 1_061
    "Warszawa - Białołęka Galeria Północna" = 1_096
    "Warszawa - Galeria Mokotów" = 1_070
    "Warszawa - Janki" = 1_069
    "Warszawa - Promenada" = 1_068
    "Warszawa - Sadyba" = 1_060
    "Wałbrzych" = 1_091
    "Wrocław - Korona" = 1_067
    "Wrocław - Wroclavia" = 1_097
    "Zielona Góra" = 1_087
    "Łódź Manufaktura" = 1_080
