blank_issues_enabled: false
contact_links:
  - name: Problem bezpieczeństwa
    url: https://github.com/kodzonko/quick-repertoire/security/policy
    about: Sprawdź politykę bezpieczeństwa i nie publikuj podatności publicznie.
