name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: ci_tests_env
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7.6.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --all-groups
      - name: Run tests
        env:
          LOGURU_LEVEL: ${{ vars.LOGURU_LEVEL }}
          DB_FILE: ${{ vars.DB_FILE }}
          USER_PREFERENCES__DEFAULT_CINEMA_VENUE: ${{ vars.USER_PREFERENCES__DEFAULT_CINEMA_VENUE }}
          USER_PREFERENCES__DEFAULT_DAY: ${{ vars.USER_PREFERENCES__DEFAULT_DAY }}
          USER_PREFERENCES__TMDB_ACCESS_TOKEN: ${{ secrets.USER_PREFERENCES__TMDB_ACCESS_TOKEN }}
          CINEMA_CITY_SETTINGS__REPERTOIRE_URL: ${{ vars.CINEMA_CITY_SETTINGS__REPERTOIRE_URL }}
          CINEMA_CITY_SETTINGS__VENUES_LIST_URL: ${{ vars.CINEMA_CITY_SETTINGS__VENUES_LIST_URL }}
        run: uv run pytest --failed-first --cov=src tests/unit tests/integration/ratings_api
